### PR TITLE
Add Monalisa color palette

### PR DESCRIPTION
**Pull request by MrPurple666**
# Pull Request

## Description

Monalisa It is a color palette based on the painting "Monalisa" by Leonardo da Vinci. 
Has been tested locally using the CLI.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Monalisa
nord

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* IGN Version:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by TheJoin95** [comment]
I like this kind of colors, is it coming directly from your idea or it already exist in other community? Of course, expect for Da Vinci eheh

**Comment by TheJoin95** [comment]
If it's possible, I'll ask to add also the palette on the website, in the ImageGoWild section so anyone can convert their assets with this palette.

If you don't want or you are not available just open an issue requesting this implementation, thank you

**Comment by MrPurple666** [comment]
> 

The 6 initial colors are purely extracted from Monalisa, I added some others colors to give the image conversion a better touch.

**Comment by MrPurple666** [comment]
> If it's possible, I'll ask to add also the palette on the website, in the ImageGoWild section so anyone can convert their assets with this palette.
> 
> If you don't want or you are not available just open an issue requesting this implementation, thank you

Certainly, I would be very grateful to have my collaboration there.

**Comment by MrPurple666** [comment]
This week I was a little busy, but as requested, I added it to the site. 
Hope everything is ok, if you need any changes let me know. :)

**Comment by TheJoin95** [comment]
Could you provide us with a screenshot of the updated website? We should add this on the PR template, but can you do it please? Thanks! You can update the first comment

**Comment by MrPurple666** [comment]
> Could you provide us with a screenshot of the updated website? We should add this on the PR template, but can you do it please? Thanks! You can update the first comment

Eh, apparently not. every time I try to open index.html it returns an empty page; i don't know if i did something wrong or i have to open it another way.

**Comment by TheJoin95** [comment]
You need to run the application in dev env locally. You can refer to this little guide: https://github.com/Schrodinger-Hat/ImageGoNord/tree/master/src/ign-frontend#project-setup

You should have installed npm and nodejs. This website is a dynamic one and the index.html it should be empty if not exececuted or built correctly

**Comment by MrPurple666** [comment]
Oh god, I forgot to comment; well i tried it several times and they all lead me to some npm/nodejs error. Sorry for the delay but I couldn't get it to run in any way.

**Comment by TheJoin95** [comment]
Closing because no new contributions on this PR

**Comment by TheJoin95** [comment]
@MrPurple666 my apologize to not bring up any kind of good documentation here.

I've created https://github.com/Schrodinger-Hat/ImageGoNord/pull/150 to implement monalisa palette.
That PR will be set as a documentation PR

I send you a lot of love and my apologize <3

**Comment by MrPurple666** [comment]
> @MrPurple666 my apologize to not bring up any kind of good documentation here.
> 
> I've created #150 to implement monalisa palette. That PR will be set as a documentation PR
> 
> I send you a lot of love and my apologize <3

WOAH, thank you very much ❤️

**Pull request closed without merging**
